### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Simpanzique** [LRYMND/volvo-rtvi#6]
Installer has syntax error, there are more ;; than needed.

**Comment by LRYMND** [comment]
I just used the wget from the readme to pull the installer and test it. For me it works fine. Can you post any additional error logs or messages please?

**Comment by Simpanzique** [comment]
Well, on line 98 there is this piece of code added"; source venv/bin/activate;;" no idea why is this in the release installer and not in the code. but i was trying it with the wget and i got this syntax error. had to remove the semicolons and it worked after i guess. Still got a few errors in the way like permissions :D

**Comment by LRYMND** [comment]
Regarding the permissions: please try to do a "chmod +x" on the Installer.

The vcan setup is implemented in the installer but the app isn't using it yet, we still need to sort this out... Probably in the next release.

If you have more issues please post the error from the console.
